### ISSUE TITLE
"JSON-Parsing-Fehler"

### ISSUE THREAD

**Issue by tromanski** [nechry/remocon2mqtt#2]
Hi,

I try to use your flow within Node-Red but I get a error message  "JSON-Parsing-Fehler" for the GetData node. The message payload node at the end brings no output because of this error. 
I tried to open the "url" https://www.remocon-net.remotethermo.com/R2/PlantHomeBsb/GetData/ extended with my gatewayId directly in chrome. This gives an error, "The resource cannot be found.". Is it possible that the URL changed? If not, what am I doing wrong?

Thank you in advance for your support.

**Comment by nechry** [comment]
hello, you can't directly open GetData url in chrome. This route (url) responds to a POST request and not a GET.
Confirming that authentication was successful, but getting data failed?
The "JSON Parse Error" may occur if you have not set a correct GatewayId, are you sure of the value provided?

You can try with the Developer console to POST the request, see: [making http requests using chrome dev tools](https://stackoverflow.com/questions/14248296/making-http-requests-using- chrome-developer-tools
)
You will have to initiate it in a TAB after you have already logged into your remocon-net account, otherwise you will not be authenticated.

**Comment by nechry** [comment]
You can also try via my new [elco-remocon-net-appdaemon](https://github.com/nechry/elco-remocon-net-appdaemon)
